Meeting 2024-01-24
oasis-tcs/openeox pull request #9
Opened 2024-01-24 16:39 UTC by sthagen

- [x] pre-meeting draft
- [ ] post-meeting draft

2024-01-24 16:46 UTC, justmurphy approved these changes
Looks good to me! Thank you, Stefan.

2024-01-24 17:58 UTC, justmurphy requested changes

2024-01-24 17:58 UTC, justmurphy commented on meeting-minutes/2024-01-24.md
> +| Tobias     | Proell     | Siemens                                                     | Member                  | ???     |
Should this be Thomas Proell?

2024-01-24 17:58 UTC, justmurphy commented on meeting-minutes/2024-01-24.md
> +| Stefan     | Arntzen    | "Huawei Technologies Co., Ltd."                             | Member                  | ???     |
Remove quotes in the company column around Huawei and Qualys on lines 19, 24, 27, & 28

2024-01-24 20:32 UTC, tschmidtb51 reviewed
Some comments and clarifications

2024-01-24 20:32 UTC, tschmidtb51 commented on meeting-minutes/2024-01-24.md
> +* Justin and Omar remind everyone, that the existing openeox organization repository at some point
```suggestion
* Justin and Omar remind everyone, that the [existing openeox organization](https://github.com/openeox) [repository](https://github.com/OpenEoX/openeox) at some point

2024-01-24 20:32 UTC, tschmidtb51 commented on meeting-minutes/2024-01-24.md
> +* All discuss
```suggestion
* All discuss
* Decision to split in 3 issues to separate the different topics:
   * [Define which EoX states are in and out of scope #7](https://github.com/oasis-tcs/openeox/issues/7)
   * [Define Common Taxonomy #11](https://github.com/oasis-tcs/openeox/issues/11)
   * [Define Mandatory vs Optional fields #12](https://github.com/oasis-tcs/openeox/issues/12)

2024-01-24 20:32 UTC, tschmidtb51 commented on meeting-minutes/2024-01-24.md
> +* skipped due to elapsed time - everyone invited to chime in per E-Mail to the TC list
```suggestion
* skipped due to elapsed time - everyone invited to chime in per email to the TC list

2024-01-24 21:26 UTC, justmurphy commented on meeting-minutes/2024-01-24.md
> +Quroum was achieved.
```suggestion
Quorum was achieved.
```

2024-01-24 21:33 UTC, justmurphy commented on meeting-minutes/2024-01-24.md
> +* [Minutes of 2023-12-07 Meeting #1 (Inaugural)](https://www.oasis-open.org/committees/document.php?document_id=71500&wg_abbrev=openeox)
```suggestion
* [Minutes of 2023-11-02 Meeting #1 (Inaugural)](https://www.oasis-open.org/committees/document.php?document_id=71500&wg_abbrev=openeox)
```

2024-01-24 21:48 UTC, justmurphy commented on meeting-minutes/2024-01-24.md
> +| Langley    | Rock.      | Dell.                                                       | Voting Member           | No      |
```suggestion
| Langley    | Rock      | Dell                                                       | Voting Member           | No      |
```

2024-01-24 21:53 UTC, justmurphy commented on meeting-minutes/2024-01-24.md
> +  *  CVE/FIRST Vuln Conf and Annual CNA Summit
```suggestion
  *  [CVE/FIRST VulnCon 2024 and Annual CNA Summit](https://www.first.org/conference/vulncon2024/)
```

2024-01-24 22:07 UTC, justmurphy reviewed
Added a few more edits and suggestions

2024-01-25 17:18 UTC, justmurphy approved these changes
Looks great!

2024-01-25 17:57 UTC, justmurphy approved these changes
Looks good.

2024-02-09 16:19 UTC, merged